[project]
name = "metaboatrace.models"
version = "0.1.0"
description = "Models of Japanese boatrace"
authors = [
    { name = "k0kishima", email = "okishimaxyz@gmail.com" }
]
dependencies = [
    "pydantic>=2.0.3",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
build-backend-path = "src"

[tool.rye]
managed = true
dev_dependencies = []
dev-dependencies = [
    "mypy>=1.4.1",
    "black>=23.7.0",
    "pytest>=7.4.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
python_version = "3.8"
check_untyped_defs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_optional = true
disallow_any_generics = true
disallow_untyped_defs = true
no_implicit_optional = true

[tool.black]
line-length = 100
target-version = ['py37']
