[project]
name = "boatrace-models"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Johndoe", email = "56298669+togane@users.noreply.github.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev_dependencies = []
dev-dependencies = [
    "mypy>=1.4.1",
]

[tool.hatch.metadata]
allow-direct-references = true
